# ------------------------------------------------------------
# Use docker-in-docker executor
# ------------------------------------------------------------
image: docker:git
services:
  - docker:dind

# ------------------------------------------------------------
# Specify CI stages
# ------------------------------------------------------------

stages:
  - test

# ------------------------------------------------------------
# 'test' stage
# ------------------------------------------------------------

test_orbkit:
  image: python:3
  stage: test
  script:
    - pip install -r requirements.txt
    - python setup.py build_ext --inplace clean
    - python -m orbkit test
    - python -m orbkit test 2
